### ISSUE TITLE
Method quickSort uses an undefined variable in return

### ISSUE THREAD

**Issue by frankvanhest** [jkoudys/immutable.php#10]
The method quickSort uses an undefined variable in return. Current variable is $imm and it should be $sfa.
While you at it, there is still a var_dump in the same method ;-)

**Comment by jkoudys** [comment]
Thanks @frankvanhest ! The `quickSort` exists purely as `protected` so it can be chosen as the default of any child classes (e.g. `class Foos extends ImmArray { public function sort(callable $cb = null) { return $this->quickSort($cb);`), so I guess not too many people are doing that right now if something I should have fixed from phpcs made it through :)
