### ISSUE TITLE
Docblock return type

### ISSUE THREAD

**Issue by Petah** [jkoudys/immutable.php#12]
Hi,

In these lines 

https://github.com/jkoudys/immutable.php/blob/master/src/Collection/ImmArray.php#L84

Shouldn't it be:

     * @return static

**Comment by svenluijten** [comment]
It can be either `static`, `self`, or `ImmArray`. Each will have the same effect on IDEs like PhpStorm and static analysis tools like PHPStan.

**Comment by Petah** [comment]
Well not if you extend the ImmArray class though.

**Comment by svenluijten** [comment]
You're right. You can submit a PR to fix this 🙂

**Comment by JarJak** [comment]
Fixed in #15
